"""Added glances,elixirs and transmutations columns

Revision ID: c74069912b35
Revises: 1a129523ca66
Create Date: 2024-12-10 13:39:56.697437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c74069912b35'
down_revision = '1a129523ca66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('glances', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('elixirs', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('transmutations', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_sources', schema=None) as batch_op:
        batch_op.drop_column('transmutations')
        batch_op.drop_column('elixirs')
        batch_op.drop_column('glances')

    # ### end Alembic commands ###
