"""Updated reflection model

Revision ID: 27fbdfb8eb03
Revises: f3ac968d0ad2
Create Date: 2024-12-10 21:07:38.448154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27fbdfb8eb03'
down_revision = 'f3ac968d0ad2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reflections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['content_sources.id'] ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_id', sa.Integer(), nullable=True))
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(
            "fk_reflections_source_id_content_sources",
            "content_sources",
            ["source_id"],
            ["id"]
        )

    with op.batch_alter_table('content_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weighted_elixirs', sa.Float(), nullable=True))

    # ### end Alembic commands ###
pass

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_sources', schema=None) as batch_op:
        batch_op.drop_column('weighted_elixirs')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('source_id')

    op.drop_table('reflections')
    # ### end Alembic commands ###
pass
