"""Fix seeder discrepency

Revision ID: 3db8d64986e3
Revises: f6e44d9ae26f
Create Date: 2025-01-05 13:03:31.170750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3db8d64986e3'
down_revision = 'f6e44d9ae26f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
